# JWT
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=kyros-app
smallrye.jwt.sign.key.location=privateKey.pem

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/agenda_db

quarkus.hibernate-orm.database.generation=drop-and-create